# Site settings
title: "Blog"
description: "Not much"
baseurl: ""
url: "http://pluhuxc.github.io"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 3

# Links
links:
  - title: "abt"
    url: /about
  - title: "git"
    url: http://github.com/alixedi
  - title: "rss"
    url: /feed.xml
